/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package office;

/**
 *
 * @author Trimurti
 */
public class Candidate extends javax.swing.JPanel {

    /**
     * Creates new form Candidate
     */
    public Candidate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbllHobby = new javax.swing.JLabel();
        txtEmailid = new javax.swing.JTextField();
        lblNationality = new javax.swing.JLabel();
        btnSaveCandidate = new javax.swing.JButton();
        lblEmailid = new javax.swing.JLabel();
        txtCandidatePassword = new javax.swing.JTextField();
        txtCandidateConfirmPassword = new javax.swing.JTextField();
        btnManagerClose = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        RadioBtnMaleCandidate = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCandidateAddress = new javax.swing.JTextArea();
        dobCandidate = new com.toedter.calendar.JDateChooser();
        txtCandidateLastName = new javax.swing.JTextField();
        txtCandidateMobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        RadioBtnFemaleCandidate = new javax.swing.JRadioButton();
        txtCandidateFirstName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setOpaque(false);

        jPanel4.setOpaque(false);

        lbllHobby.setBackground(new java.awt.Color(255, 255, 255));
        lbllHobby.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbllHobby.setForeground(new java.awt.Color(255, 255, 255));
        lbllHobby.setText("Hobby:");

        lblNationality.setBackground(new java.awt.Color(255, 255, 255));
        lblNationality.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNationality.setForeground(new java.awt.Color(255, 255, 255));
        lblNationality.setText("Nationality:");

        btnSaveCandidate.setBackground(new java.awt.Color(122, 89, 128));
        btnSaveCandidate.setText("Save");
        btnSaveCandidate.setBorder(null);
        btnSaveCandidate.setOpaque(false);
        btnSaveCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCandidateActionPerformed(evt);
            }
        });

        lblEmailid.setBackground(new java.awt.Color(255, 255, 255));
        lblEmailid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailid.setForeground(new java.awt.Color(255, 255, 255));
        lblEmailid.setText("Email-id:");

        btnManagerClose.setBackground(new java.awt.Color(122, 89, 128));
        btnManagerClose.setText("Cancel");
        btnManagerClose.setBorder(null);
        btnManagerClose.setOpaque(false);
        btnManagerClose.setPreferredSize(new java.awt.Dimension(43, 17));
        btnManagerClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNationality))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmailid, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtCandidatePassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCandidateConfirmPassword)
                        .addContainerGap())))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnManagerClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnSaveCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllHobby, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCandidatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCandidateConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagerClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        RadioBtnMaleCandidate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioBtnMaleCandidate.setForeground(new java.awt.Color(255, 255, 255));
        RadioBtnMaleCandidate.setText("Male");
        RadioBtnMaleCandidate.setOpaque(false);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date of Birth:");

        txtCandidateAddress.setColumns(20);
        txtCandidateAddress.setRows(5);
        jScrollPane2.setViewportView(txtCandidateAddress);

        dobCandidate.setDateFormatString("dd,MM, yyyy");

        txtCandidateMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCandidateMobileActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address");

        RadioBtnFemaleCandidate.setBackground(new java.awt.Color(255, 255, 255));
        RadioBtnFemaleCandidate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RadioBtnFemaleCandidate.setForeground(new java.awt.Color(204, 204, 204));
        RadioBtnFemaleCandidate.setText("Female");
        RadioBtnFemaleCandidate.setOpaque(false);

        txtCandidateFirstName.setText(LoginInterface.FIRSTNAME);
        txtCandidateFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCandidateFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCandidateFirstNameFocusLost(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender:");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Last Name:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Mobile no.:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(RadioBtnMaleCandidate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioBtnFemaleCandidate))
                    .addComponent(txtCandidateMobile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(txtCandidateLastName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCandidateFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobCandidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCandidateFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCandidateLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCandidateMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RadioBtnMaleCandidate)
                        .addComponent(RadioBtnFemaleCandidate)))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(dobCandidate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCandidateActionPerformed
        // TODO add your handling code here:
        
        HomeAdmin.getHomeAdmin().registerCandidateAction();
    }//GEN-LAST:event_btnSaveCandidateActionPerformed

    private void txtCandidateMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCandidateMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCandidateMobileActionPerformed

    private void btnManagerCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagerCloseActionPerformed

    private void txtCandidateFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCandidateFirstNameFocusGained
        // TODO add your handling code here:
        if(evt.getSource()==txtCandidateFirstName){
            if(txtCandidateFirstName.getText().equals(LoginInterface.FIRSTNAME)){
                txtCandidateFirstName.setText("");
            }
        }
    }//GEN-LAST:event_txtCandidateFirstNameFocusGained

    private void txtCandidateFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCandidateFirstNameFocusLost
        // TODO add your handling code here:
        if(evt.getSource()==txtCandidateFirstName){
            if(txtCandidateFirstName.getText().equals("")){
                txtCandidateFirstName.setText(LoginInterface.FIRSTNAME);
            }
        }
        
    }//GEN-LAST:event_txtCandidateFirstNameFocusLost

     public java.util.Date getCandidateDOB(){
        return dobCandidate.getDate();
    }
    public String getCandidateFirstName() {
        return txtCandidateFirstName.getText();
    }
    public String getCandidateLastName(){
        return txtCandidateLastName.getText();
    }
    public String getCandidateAddress(){
        return txtCandidateAddress.getText();
    }
    
    public String getCandidateMobile(){
        return txtCandidateMobile.getText();
    }
    public String getCandidateGender(){
        if(RadioBtnMaleCandidate.isSelected())
        {
            return "Male";
        }
        return "Female";
    }
        public String getCandidateEmailid(){
        return txtEmailid.getText();
    }
    public String getCandidateHobby(){
        return txtCandidatePassword.getText();
    }
    public String getCandidateNationality(){
        return txtCandidateConfirmPassword.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioBtnFemaleCandidate;
    private javax.swing.JRadioButton RadioBtnMaleCandidate;
    private javax.swing.JButton btnManagerClose;
    private javax.swing.JButton btnSaveCandidate;
    private com.toedter.calendar.JDateChooser dobCandidate;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmailid;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lbllHobby;
    private javax.swing.JTextArea txtCandidateAddress;
    private javax.swing.JTextField txtCandidateConfirmPassword;
    private javax.swing.JTextField txtCandidateFirstName;
    private javax.swing.JTextField txtCandidateLastName;
    private javax.swing.JTextField txtCandidateMobile;
    private javax.swing.JTextField txtCandidatePassword;
    private javax.swing.JTextField txtEmailid;
    // End of variables declaration//GEN-END:variables

    

 }
